### ISSUE TITLE
Issue with socket.io dependency

### ISSUE THREAD

**Issue by dgershman** [BarkingMouseStudio/redis-viewer#4]
There seems to be an issue with the socket.io dependency in package.json.  Once I remove it everything works good.  This should probably be updated and committed.

**Comment by gordoncww** [comment]
Seeing the same thing here:

```
% npm install
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/less
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/hiredis
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/redis
npm http 304 https://registry.npmjs.org/hiredis
npm http 304 https://registry.npmjs.org/less
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/socket.io/-/socket.io-0.6.18.tgz
npm http 200 https://registry.npmjs.org/socket.io/-/socket.io-0.6.18.tgz
npm ERR! error reading /var/folders/xx/7s2mhwy94f5f3l7q7v_xqvd40000gp/T/npm-1346279365282/1346279365282-0.7140498110093176/package
npm ERR! couldn't pack /var/folders/xx/7s2mhwy94f5f3l7q7v_xqvd40000gp/T/npm-1346279365282/1346279365282-0.7140498110093176/package to /Users/gordon/.npm/socket.io/0.6.18/package.tgz

npm ERR! SyntaxError: Unexpected token }
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:179:33)
npm ERR!     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at [object Object].<anonymous> (fs.js:151:5)
npm ERR!     at [object Object].emit (events.js:84:17)
npm ERR!     at fs.js:1266:12
npm ERR!     at Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/gordon/code/redis-viewer
npm ERR! node -v v0.7.9-pre
npm ERR! npm -v 1.1.18
npm ERR! file /var/folders/xx/7s2mhwy94f5f3l7q7v_xqvd40000gp/T/npm-1346279365282/1346279365282-0.7140498110093176/package/support/socket.io-client/lib/vendor/uglifyjs/package.json
npm ERR! path /var/folders/xx/7s2mhwy94f5f3l7q7v_xqvd40000gp/T/npm-1346279365282/1346279365282-0.7140498110093176/package/support/socket.io-client/lib/vendor/uglifyjs
npm ERR! type unexpected_token
npm ERR! fstream_path /var/folders/xx/7s2mhwy94f5f3l7q7v_xqvd40000gp/T/npm-1346279365282/1346279365282-0.7140498110093176/package/support/socket.io-client/lib/vendor/uglifyjs
npm ERR! fstream_type Directory
npm ERR! fstream_class Packer
npm ERR! arguments [ '}' ]
npm ERR! message Unexpected token }
npm ERR! fstream_stack Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:182:10)
npm ERR! fstream_stack Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR! fstream_stack [object Object].<anonymous> (fs.js:151:5)
npm ERR! fstream_stack [object Object].emit (events.js:84:17)
npm ERR! fstream_stack fs.js:1266:12
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)

npm ERR! TypeError: Cannot call method 'filter' of undefined
npm ERR!     at Packer.addIgnoreRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:148:13)
npm ERR!     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:133:10)
npm ERR!     at [object Object].<anonymous> (fs.js:151:5)
npm ERR!     at [object Object].emit (events.js:84:17)
npm ERR!     at fs.js:1266:12
npm ERR!     at Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/gordon/code/redis-viewer
npm ERR! node -v v0.7.9-pre
npm ERR! npm -v 1.1.18
npm ERR! type non_object_property_call
npm ERR! arguments [ 'filter', undefined ]
npm ERR! message Cannot call method 'filter' of undefined
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/gordon/code/redis-viewer/npm-debug.log
npm not ok
```

**Comment by dgershman** [comment]
I want to submit some changes to this, but I'm unfamiliar with the process.  What should I do?

**Comment by ashrocket** [comment]
I had the same issue.  Pinned socket.io to 0.6.17 for now and it works

 "dependencies": {
    "coffee-script": "1.1",
    "less": "1",
    "express": "2",
    "socket.io": "0.6.17",
    "underscore": "1",
    "optimist": "0.1",
    "redis": "0.6",
    "hiredis": "0.1"
  }
